# Optimizing Models


#### Import Tools

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# sklearn 
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, \
    precision_recall_curve, roc_curve, roc_auc_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.preprocessing import StandardScaler

#### Import Data

In [2]:
avi = pd.read_csv('SnowWeatherCleanROS.csv')
avi.head()

Unnamed: 0  avi_danger  avg_wind  temp_max_swing  temp_max_swing_from_avg  \
0           0         1.0     20.58             0.0                      0.0   
1           1         3.0     35.12             3.0                      0.0   
2           2         2.0     33.78            -3.0                      0.0   
3           3         3.0     31.32             0.0                      0.0   
4           4         2.0     32.44             2.0                      1.4   

     year  month   day  temp_max  temp_min  ...  prevailing_wind_N_2  \
0  2010.0   12.0  20.0        15         5  ...                  0.0   
1  2010.0   12.0  21.0        18        10  ...                  0.0   
2  2010.0   12.0  22.0        15         7  ...                  1.0   
3  2010.0   12.0  23.0        15         6  ...                  1.0   
4  2010.0   12.0  24.0        17         9  ...                  1.0   

   prevailing_wind_NE_2  prevailing_wind_NW_2  prevailing_wind_S_2  \
0                   0.0                   1.0                  0.0   
1                   0.0                   1.0                  0.0   
2                   0.0                   0.0                  0.0   
3                   0.0                   0.0                  0.0   
4                   0.0                   0.0                  0.0   

   prevailing_wind_SE_2  prevailing_wind_SW_2  prevailing_wind_W_2  \
0                   0.0                   0.0                  0.0   
1                   0.0                   0.0                  0.0   
2                   0.0                   0.0                  0.0   
3                   0.0                   0.0                  0.0   
4                   0.0                   0.0                  0.0   

   three_day_snow_2  five_day_snow_2  next_day_avi_danger  
0               0.2              0.2                  3.0  
1               0.3              0.3                  2.0  
2               2.5              2.5                  3.0  
3               4.3              4.5                  2.0  
4               8.3              8.6                  2.0  

[5 rows x 74 columns]

In [3]:
avi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1876 entries, 0 to 1875
Data columns (total 74 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Unnamed: 0                 1876 non-null   int64  
 1   avi_danger                 1876 non-null   float64
 2   avg_wind                   1876 non-null   float64
 3   temp_max_swing             1876 non-null   float64
 4   temp_max_swing_from_avg    1876 non-null   float64
 5   year                       1876 non-null   float64
 6   month                      1876 non-null   float64
 7   day                        1876 non-null   float64
 8   temp_max                   1876 non-null   int64  
 9   temp_min                   1876 non-null   int64  
 10  water_equivalent           1876 non-null   float64
 11  snow_fall                  1876 non-null   float64
 12  snow_depth_6am             1876 non-null   float64
 13  wind_speed_sum             1876 non-null   int64

#### filter data

In [4]:
avi = avi.drop(['Unnamed: 0'], axis=1)

In [5]:
# avi = avi.drop(['prevailing_wind_E', 'prevailing_wind_N', 'prevailing_wind_NE', 'prevailing_wind_NW',
#                 'prevailing_wind_S', 'prevailing_wind_SE', 'prevailing_wind_SW', 'prevailing_wind_W',
#                 'prevailing_wind_E_1', 'prevailing_wind_N_1', 'prevailing_wind_NE_1', 'prevailing_wind_NW_1',
#                 'prevailing_wind_S_1', 'prevailing_wind_SE_1', 'prevailing_wind_SW_1', 'prevailing_wind_W_1',
#                 'prevailing_wind_E_2', 'prevailing_wind_N_2', 'prevailing_wind_NE_2', 'prevailing_wind_NW_2',
#                 'prevailing_wind_S_2', 'prevailing_wind_SE_2', 'prevailing_wind_SW_2', 'prevailing_wind_W_2'], axis=1)

#### Splitting Dataset

In [6]:
x = avi.iloc[:, 0:avi.shape[1]-1]
y = avi.iloc[:, avi.shape[1]-1]

print(x.shape)
print(y.shape)

(1876, 72)
(1876,)


#### Standardizing

In [7]:
#standardizer 
def standardize(X_train, X_test):
    scaler = StandardScaler()
    # Fitting and transforming training data
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    # Tranforming testing data based on traning fit (prevent data leakage)
    X_test = scaler.transform(X_test)
    return X_train, X_test

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

# Scaling
x_train, x_test = standardize(x_train, x_test)

In [9]:
print(y)

(unique, counts) = np.unique(y, return_counts=True)
frequencies = np.asarray((unique, counts)).T

print(frequencies)

0       3.0
1       2.0
2       3.0
3       2.0
4       2.0
       ... 
1871    4.0
1872    4.0
1873    4.0
1874    4.0
1875    4.0
Name: next_day_avi_danger, Length: 1876, dtype: float64
[[  1. 469.]
 [  2. 469.]
 [  3. 469.]
 [  4. 469.]]


### Random Forest

In [10]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}


rf = RandomForestClassifier(class_weight = "balanced")
rf_cv = RandomizedSearchCV(estimator=rf, param_distributions=random_grid, n_iter=5, scoring='f1_weighted')
rf_cv.fit(x_train, y_train)
y_pred_rf = rf_cv.predict(x_test)
print(accuracy_score(y_test, y_pred_rf))
print(cross_val_score(rf, x_train, y_train, cv=3))

0.8187633262260128
[0.75906183 0.74200426 0.76759062]


In [24]:
print(rf_cv.best_params_)

{'n_estimators': 200, 'min_samples_split': 2, 'min_samples_leaf': 2, 'max_features': 'auto', 'max_depth': 100, 'bootstrap': False}


In [11]:
print(confusion_matrix(y_test, y_pred_rf))

[[ 92  15   4   0]
 [ 17  86  17   1]
 [  7  22  88   2]
 [  0   0   0 118]]


In [12]:
print(classification_report(y_test, y_pred_rf))

              precision    recall  f1-score   support

         1.0       0.79      0.83      0.81       111
         2.0       0.70      0.71      0.70       121
         3.0       0.81      0.74      0.77       119
         4.0       0.98      1.00      0.99       118

    accuracy                           0.82       469
   macro avg       0.82      0.82      0.82       469
weighted avg       0.82      0.82      0.82       469



### Extra Forest

In [13]:
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

et = ExtraTreesClassifier(class_weight = "balanced")
et_cv = RandomizedSearchCV(estimator=et, param_distributions=random_grid, n_iter=5, scoring='f1_weighted')
et_cv.fit(x_train, y_train)
y_pred_et = et_cv.predict(x_test)
print(accuracy_score(y_test, y_pred_et))
print(cross_val_score(rf, x_train, y_train, cv=3))

0.8123667377398721
[0.76545842 0.77185501 0.7761194 ]


In [25]:
print(et_cv.best_params_)

{'n_estimators': 1800, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'sqrt', 'max_depth': 80, 'bootstrap': True}


In [14]:
print(confusion_matrix(y_test, y_pred_et))

[[ 95  12   4   0]
 [ 22  78  21   0]
 [  7  20  90   2]
 [  0   0   0 118]]


In [15]:
print(classification_report(y_test, y_pred_et))

              precision    recall  f1-score   support

         1.0       0.77      0.86      0.81       111
         2.0       0.71      0.64      0.68       121
         3.0       0.78      0.76      0.77       119
         4.0       0.98      1.00      0.99       118

    accuracy                           0.81       469
   macro avg       0.81      0.81      0.81       469
weighted avg       0.81      0.81      0.81       469



## Gradient Boosting Classifier

In [21]:
param_distributions = {'learning_rate':[0.15,0.1,0.05,0.01,0.005,0.001], 
                       'n_estimators':[100,250,500,750,1000,1250,1500,1750],
                       'max_depth':[2,3,4,5,6,7] }

gbc = GradientBoostingClassifier(n_estimators=500, max_depth=4, learning_rate=0.05)
# gbc_cv = RandomizedSearchCV(estimator=gbc, param_distributions= param_distributions, n_iter=5, scoring='f1_weighted')
gbc.fit(x_train, y_train)
y_pred_gbc = gbc.predict(x_test)
print(accuracy_score(y_test, y_pred_gbc))
print(cross_val_score(gbc, x_train, y_train, cv=3))

# print(gbc_cv.best_params_)
# {'n_estimators': 500, 'max_depth': 4, 'learning_rate': 0.05}

0.8187633262260128
[0.76759062 0.73773987 0.73987207]


In [22]:
print(confusion_matrix(y_test, y_pred_gbc))

[[ 90  14   6   1]
 [ 18  84  18   1]
 [  6  15  92   6]
 [  0   0   0 118]]


In [23]:
print(classification_report(y_test, y_pred_gbc))

              precision    recall  f1-score   support

         1.0       0.79      0.81      0.80       111
         2.0       0.74      0.69      0.72       121
         3.0       0.79      0.77      0.78       119
         4.0       0.94      1.00      0.97       118

    accuracy                           0.82       469
   macro avg       0.82      0.82      0.82       469
weighted avg       0.82      0.82      0.82       469

